AllCops:
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'